dependencies:
- alias:  expose
  name: exposecontroller
  repository: file://../exposecontroller
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: file://../exposecontroller
  version: 2.3.82
- name: micro
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.33
